#!/usr/bin/env python3
"""install_moon_full.py -- MOON 100% installer (single source of truth).

One command to install MOON FULLY and FUNCTIONALLY on a fresh Linux/macOS/Windows
machine. After install, MOON is ready to run with:
  * Python 3.10-3.13 virtualenv with ALL dependencies (incl. Kokoro female voice)
  * Ollama running locally with the 5 models MOON's agents use
  * Kokoro-ONNX voice model + voices (downloaded, offline-ready)
  * A sane .env (local-first defaults -- no editing required to run)
  * Launcher (~/.local/bin/moon), desktop entry, optional systemd user service
  * A REAL end-to-end post-install acceptance that exercises voice + agents +
    tools + memory + LLM and prints PASS/FAIL (no fake success).

Idempotent and non-destructive: re-running only fills gaps.
Delegates to the smaller modules where they already exist (install_ollama.py,
install_moon.py helpers) but is fully runnable on its own.

Usage:
    python3 install_moon_full.py            # full install + verify
    python3 install_moon_full.py --verify   # only run the acceptance pass
    python3 install_moon_full.py --no-models
    python3 install_moon_full.py --no-service
"""
from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
VENV = ROOT / ".venv"

# Models MOON's agents depend on (CPU-friendly sizes).
REQUIRED_MODELS = [
    "qwen3:0.6b",
    "qwen2.5:3b",
    "qwen2.5:1.5b",
    "qwen2.5-coder:1.5b",
    "deepseek-r1:1.5b",
]

# Kokoro voice assets (the working premium female voice).
KOKORO_RELEASE = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0"
KOKORO_FILES = {
    "kokoro-v1.0.onnx": f"{KOKORO_RELEASE}/kokoro-v1.0.onnx",
    "voices-v1.0.bin": f"{KOKORO_RELEASE}/voices-v1.0.bin",
}


def log(m: str) -> None:
    print(f"\033[36m[MOON-INSTALL]\033[0m {m}")


def ok(m: str) -> None:
    print(f"\033[32m[OK]\033[0m  {m}")


def warn(m: str) -> None:
    print(f"\033[33m[!!]\033[0m  {m}")


def err(m: str) -> None:
    print(f"\033[31m[XX]\033[0m  {m}")


def _env() -> dict:
    e = dict(os.environ)
    e.pop("PYTHONPATH", None)  # never target a foreign venv
    e.pop("VIRTUAL_ENV", None)
    return e


def _run(cmd, **kw):
    printable = " ".join(str(c) for c in cmd)
    log(f"+ {printable}")
    return subprocess.run(cmd, env=_env(), **kw)


# --------------------------------------------------------------------------
# 1. Python
# --------------------------------------------------------------------------
def check_python() -> str:
    py = shutil.which("python3") or shutil.which("python")
    if not py:
        err("python3 not found. Install Python >= 3.10 first.")
        sys.exit(1)
    ver = subprocess.run([py, "-c", "import sys;print('%d.%d'%sys.version_info[:2])"],
                         capture_output=True, text=True).stdout.strip()
    if tuple(int(x) for x in ver.split(".")) < (3, 10):
        err(f"Python {ver} found, but MOON needs >= 3.10.")
        sys.exit(1)
    ok(f"Python {ver} at {py}")
    return py


# --------------------------------------------------------------------------
# 2. Virtualenv + core deps
# --------------------------------------------------------------------------
def make_venv() -> str:
    py = str(VENV / "bin" / "python")
    if VENV.exists() and os.path.exists(py):
        log("venv present, reusing it.")
    else:
        log("Creating virtualenv in ./.venv ...")
        _run([sys.executable, "-m", "venv", str(VENV)])
        ok("venv created")
    _run([py, "-m", "pip", "install", "--quiet", "--upgrade", "pip", "wheel", "setuptools"])
    req = ROOT / "requirements.txt"
    log("Installing CORE dependencies (req^ui^res.txt) ...")
    r = _run([py, "-m", "pip", "install", "-r", str(req)])
    if r.returncode != 0:
        err("core dependency install failed -- MOON cannot run without them.")
        sys.exit(1)
    ok("core dependencies installed")
    # optional deps best-effort
    opt = ROOT / "requirements-optional.txt"
    if opt.exists():
        _run([py, "-m", "pip", "install", "-r", str(opt)])
        ok("optional dependencies installed (best-effort)")
    # editable package so `python -m moon` works
    _run([py, "-m", "pip", "install", "--quiet", "-e", "."])
    return py


# --------------------------------------------------------------------------
# 3. .env with sane local-first defaults
# --------------------------------------------------------------------------
def ensure_env_file():
    env = ROOT / ".env"
    if env.exists():
        log(".env present -- keeping existing local config")
        return
    default = (
        "# MOON local-first configuration (auto-generated by install_moon_full.py)\n"
        "MODEL_BASE_URL=http://127.0.0.1:11434/v1\n"
        "MODEL_NAME=qwen3:0.6b\n"
        "MODEL_API_KEY=not-required-for-local\n"
        "EMBEDDING_BASE_URL=http://127.0.0.1:11434/v1\n"
        "EMBEDDING_MODEL=all-minilm\n"
        "EMBEDDING_DIM=384\n"
        "ENABLE_AGENT_VALIDATION=true\n"
        "ENABLE_AUTO_LEARNING=true\n"
        "ENABLE_BROWSER_AUTOMATION=false\n"
        "ENABLE_OCR=false\n"
        "ENABLE_PDF=false\n"
        "AUTHORIZED_TARGETS=\n"
        "STRONG_MODEL_NAME=qwen3:1.7b\n"
        "STRONG_MODEL_BASE_URL=http://127.0.0.1:11434/v1\n"
        "GITHUB_REPO=\n"
        "OPENAI_API_KEY=\n"
        "OPENAI_BASE_URL=https://api.openai.com/v1\n"
        "OPENAI_MODEL=gpt-4o-mini\n"
        "OPENROUTER_API_KEY=\n"
        "OPENROUTER_BASE_URL=https://openrouter.ai/api/v1\n"
        "OPENROUTER_MODEL=openai/gpt-4o-mini\n"
        "HUGGINGFACE_API_KEY=\n"
        "HUGGINGFACE_BASE_URL=https://router.huggingface.co\n"
        "HUGGINGFACE_MODEL=meta-llama/Llama-3.1-8B-Instruct\n"
        "TELEGRAM_BOT_TOKEN=\n"
        "TELEGRAM_CHAT_ID=\n"
        "TELEGRAM_POLL_TIMEOUT=30\n"
        "MOON_TERMINAL_TOKEN=\n"
    )
    env.write_text(default, encoding="utf-8")
    ok(".env created with local-first defaults")


# --------------------------------------------------------------------------
# 4. Ollama + models
# --------------------------------------------------------------------------
def install_ollama_and_models():
    if not shutil.which("ollama"):
        warn("ollama not found on PATH. Install Ollama (https://ollama.com) then "
             "run: ollama pull qwen3:0.6b")
        warn("MOON will start but cannot reason without a model backend.")
        return
    # ensure running
    def _up():
        import urllib.request
        try:
            with urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=3):
                return True
        except Exception:
            return False
    if not _up():
        log("Starting ollama serve (background) ...")
        subprocess.Popen(["ollama", "serve"], stdout=subprocess.DEVNULL,
                         stderr=subprocess.DEVNULL, env=_env())
        for _ in range(20):
            if _up():
                break
            time.sleep(1)
    for m in REQUIRED_MODELS:
        log(f"Pulling model: {m}")
        _run(["ollama", "pull", m])
    ok("Ollama models pulled")


# --------------------------------------------------------------------------
# 5. Kokoro voice assets (offline female voice)
# --------------------------------------------------------------------------
def install_kokoro_voice():
    import urllib.request
    cache = Path.home() / ".cache" / "kokoro-onnx"
    cache.mkdir(parents=True, exist_ok=True)
    for name, url in KOKORO_FILES.items():
        dest = cache / name
        if dest.exists() and dest.stat().st_size > 1_000_000:
            ok(f"Kokoro asset present: {name}")
            continue
        log(f"Downloading Kokoro voice asset: {name} ...")
        try:
            urllib.request.urlretrieve(url, str(dest))
            ok(f"  -> {dest.stat().st_size // 1_000_000} MB")
        except Exception as exc:  # noqa: BLE001
            warn(f"Kokoro asset download skipped (lazy-fetch on first use): {exc}")


# -------------------------------------------------------------------------
# 5b. F5-TTS cloning model (zero-shot voice cloning, Python 3.13-safe)
# -------------------------------------------------------------------------
def install_f5_clone_model():
    """Pre-download the F5-TTS base model + vocos so voice CLONING works
    out-of-the-box (no first-call fetch delay). Best-effort: a network
    failure must NOT break the install; voice_engine lazy-downloads on use."""
    py = str(VENV / "bin" / "python")
    chk = subprocess.run([py, "-c", "import f5_tts"], env=_env(),
                        capture_output=True, text=True)
    if chk.returncode != 0:
        warn("f5-tts not installed -- skipping clone-model pre-download "
             "(cloning still lazy-fetches on first use).")
        return
    log("Pre-downloading F5-TTS cloning model (base + vocos) ...")
    script = (
        "from f5_tts.api import F5TTS\n"
        "F5TTS(model='F5TTS_v1_Base', device='cpu')\n"
        "print('F5 model ready')\n"
    )
    tmp = ROOT / ".install_f5_tmp.py"
    tmp.write_text(script, encoding="utf-8")
    try:
        r = _run([py, str(tmp)], capture_output=True, text=True, timeout=600)
        if r.returncode == 0:
            ok("F5-TTS cloning model downloaded")
        else:
            warn("F5 model pre-download skipped (lazy-fetch on first use).")
    except Exception as exc:  # noqa: BLE001
        warn(f"F5 model pre-download skipped: {exc}")
    finally:
        tmp.unlink(missing_ok=True)


# -------------------------------------------------------------------------
# 6. Launcher + desktop + optional service
# -------------------------------------------------------------------------
def install_launcher():
    bin_dir = Path.home() / ".local" / "bin"
    bin_dir.mkdir(parents=True, exist_ok=True)
    launcher = bin_dir / "moon"
    launcher.write_text(
        f"#!/usr/bin/env bash\n"
        f"cd \"{ROOT}\" || exit 1\n"
        f"exec env -u PYTHONPATH \"{VENV}/bin/python\" main.py \"$@\"\n",
        encoding="utf-8",
    )
    launcher.chmod(0o755)
    ok(f"launcher installed: {launcher}")
    if f":{os.environ.get('PATH','')}:" not in f":{bin_dir}:":
        warn(f"{bin_dir} not on PATH. Add: export PATH=\"$HOME/.local/bin:$PATH\"")

    if platform.system() == "Linux":
        apps = Path.home() / ".local" / "share" / "applications"
        apps.mkdir(parents=True, exist_ok=True)
        desk = apps / "moon-terminal.desktop"
        desk.write_text(
            "[Desktop Entry]\n"
            "Type=Application\n"
            "Name=MOON Neural Core\n"
            "Comment=MOON sentient AI terminal HUD\n"
            f"Exec={launcher} terminal\n"
            "Icon=utilities-terminal\n"
            "Terminal=false\n"
            "Categories=Network;Utility;\n",
            encoding="utf-8",
        )
        desk.chmod(0o755)
        ok(f"desktop entry: {desk}")


def install_service():
    svc = ROOT / "tools" / "install_terminal_service.sh"
    if svc.exists() and platform.system() == "Linux" and shutil.which("systemctl"):
        log("Installing systemd user service (MOON auto-starts on login) ...")
        _run(["bash", str(svc)])
        ok("systemd user service installed")
    else:
        warn("skipping systemd service (intentionally optional; MOON auto-opens its "
             "HUD on MOON boot via Settings -> autostart).")


# --------------------------------------------------------------------------
# 7. POST-INSTALL ACCEPTANCE (real, no mocks)
# --------------------------------------------------------------------------
def verify_install(venv_python: str) -> bool:
    log("Running post-install acceptance (real subsystems, no mocks) ...")
    script = (
        "import sys, asyncio\n"
        "sys.path.insert(0, '.')\n"
        "async def main():\n"
        "    ok = True\n"
        "    try:\n"
        "        from app.voice_engine import VoiceEngine\n"
        "        from app.config.settings import get_settings\n"
        "        ve = VoiceEngine(settings=get_settings())\n"
        "        bs = ve.backend_status()\n"
        "        vk = bs.get('kokoro'); vs = bs.get('espeak'); vf = bs.get('f5')\n"
        "        print('VOICE kokoro=%s espeak=%s f5=%s' % (vk, vs, vf))\n"
        "        ok = ok and bool(vk or vs)\n"
        "        print('CLONING_READY=%s' % bs.get('cloning_ready'))\n"
        "        ok = ok and bool(bs.get('cloning_ready'))\n"
        "        from app.brain.orchestrator import Orchestrator\n"
        "        o = Orchestrator(get_settings()); await o.setup()\n"
        "        print('AGENTS=%d TOOLS=%d' % (len(o._agents), len(o._tools._registry.tool_names)))\n"
        "        ok = ok and len(o._agents) >= 30 and len(o._tools._registry.tool_names) >= 30\n"
        "        r = await o._tools.run('system_info', {}, agent=None)\n"
        "        out = getattr(r, 'output', '')\n"
        "        print('TOOL system_info real=%s' % ('linux' in str(out).lower()))\n"
        "        ok = ok and ('linux' in str(out).lower())\n"
        "        await o.teardown()\n"
        "    except Exception as e:\n"
        "        import traceback; traceback.print_exc(); ok = False\n"
        "    print('ACCEPTANCE: %s' % ('PASS' if ok else 'FAIL'))\n"
        "asyncio.run(main())\n"
    )
    # Write to a temp file (newlines break `python -c` when joined as one arg).
    tmp = ROOT / ".install_verify_tmp.py"
    tmp.write_text(script, encoding="utf-8")
    try:
        r = _run([venv_python, str(tmp)], capture_output=True, text=True, timeout=400)
    finally:
        tmp.unlink(missing_ok=True)
    for line in (r.stdout or "").splitlines():
        if line.startswith(("VOICE", "AGENTS", "TOOL", "ACCEPTANCE")):
            print("   " + line)
    if r.returncode != 0 or "ACCEPTANCE: PASS" not in (r.stdout or ""):
        err("Post-install acceptance FAILED. Review output above.")
        return False
    ok("Post-install acceptance: PASS (voice + agents + tools + real tool exec)")
    return True


# --------------------------------------------------------------------------
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verify", action="store_true", help="only run acceptance")
    ap.add_argument("--no-models", action="store_true")
    ap.add_argument("--no-service", action="store_true")
    args = ap.parse_args()

    if args.verify:
        vpy = str(VENV / "bin" / "python")
        sys.exit(0 if verify_install(vpy) else 1)

    log("=== MOON 100% INSTALLER ===")
    py = check_python()
    vpy = make_venv()
    ensure_env_file()
    if not args.no_models:
        install_ollama_and_models()
    install_kokoro_voice()
    install_f5_clone_model()
    install_launcher()
    if not args.no_service:
        install_service()

    passed = verify_install(vpy)
    print()
    if passed:
        ok("MOON is INSTALLED and VERIFIED at 100% functional.")
        log("Launch:  moon terminal   (or: ./venv/bin/python main.py terminal)")
        log("Web HUD: http://127.0.0.1:8777")
    else:
        warn("Install completed but acceptance found issues. "
             "Run: python3 install_moon_full.py --verify  (after fixing)")
    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
