"""install_moon.py -- bootstrap MOON on a fresh machine.

Creates an isolated environment, fetches runtime dependencies, and (best-effort)
the voice stack. Heavy framework requirements are pulled via requirements.txt.
"""

import argparse
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
_PKG = "pip"

# Models Moon needs so every agent is ready out of the box (CPU-friendly sizes).
# Pulled best-effort; larger models can be added later on a capable host.
REQUIRED_MODELS = [
    "qwen3:0.6b",
    "qwen2.5:3b",
    "qwen2.5:1.5b",
    "qwen2.5-coder:1.5b",
    "deepseek-r1:1.5b",
]


def install_models():
    """Best-effort: ensure Ollama is up and pull the models Moon's agents use."""
    import shutil

    exe = shutil.which("ollama")
    if exe is None:
        print("ollama not found on PATH -- skipping model pull. Install Ollama "
              "(https://ollama.com) then run: ollama pull qwen3:0.6b")
        return
    # Start the service if needed.
    import urllib.request

    def _up():
        try:
            with urllib.request.urlopen("http://127.0.0.1:11434/api/tags", timeout=3):
                return True
        except Exception:
            return False

    if not _up():
        print("Starting ollama serve (background)...")
        subprocess.Popen([exe, "serve"], stdout=subprocess.DEVNULL,
                         stderr=subprocess.DEVNULL)
        for _ in range(20):
            if _up():
                break
            time.sleep(1)
    for m in REQUIRED_MODELS:
        print(f"Pulling model: {m}")
        _run([exe, "pull", m])


def ensure_env_file():
    """Create .env from .env.example if absent (secrets never committed).

    Unlike a naive copy of .env.example (which contains literal '<set>'
    placeholders), we materialise sane *working* defaults so a fresh install
    runs immediately against the local Ollama backend without the operator
    having to edit anything. Cloud-only keys stay blank (graceful fallback).
    """
    env = ROOT / ".env"
    if env.exists():
        print(".env present -- keeping existing local config")
        return
    default_env = (
        "# MOON local-first configuration (auto-generated by install_moon.py)\n"
        "MODEL_BASE_URL=http://127.0.0.1:11434/v1\n"
        "MODEL_NAME=qwen3:0.6b\n"
        "MODEL_API_KEY=not-required-for-local\n"
        "EMBEDDING_BASE_URL=http://127.0.0.1:11434/v1\n"
        "EMBEDDING_MODEL=all-minilm\n"
        "EMBEDDING_DIM=384\n"
        "ENABLE_AGENT_VALIDATION=true\n"
        "ENABLE_AUTO_LEARNING=true\n"
        "ENABLE_BROWSER_AUTOMATION=false\n"
        "ENABLE_OCR=false\n"
        "ENABLE_PDF=false\n"
        "AUTHORIZED_TARGETS=\n"
        "STRONG_MODEL_NAME=qwen3:1.7b\n"
        "STRONG_MODEL_BASE_URL=http://127.0.0.1:11434/v1\n"
        "GITHUB_REPO=\n"
        "OPENAI_API_KEY=\n"
        "OPENAI_BASE_URL=https://api.openai.com/v1\n"
        "OPENAI_MODEL=gpt-4o-mini\n"
        "OPENROUTER_API_KEY=\n"
        "OPENROUTER_BASE_URL=https://openrouter.ai/api/v1\n"
        "OPENROUTER_MODEL=openai/gpt-4o-mini\n"
        "HUGGINGFACE_API_KEY=\n"
        "HUGGINGFACE_BASE_URL=https://router.huggingface.co\n"
        "HUGGINGFACE_MODEL=meta-llama/Llama-3.1-8B-Instruct\n"
        "TELEGRAM_BOT_TOKEN=\n"
        "TELEGRAM_CHAT_ID=\n"
        "TELEGRAM_POLL_TIMEOUT=30\n"
        "MOON_TERMINAL_TOKEN=\n"
    )
    env.write_text(default_env, encoding="utf-8")
    print(".env created with local-first defaults (fill cloud keys to enable fallbacks)")


def _run(cmd, env=None):
    print("+", " ".join(cmd))
    # Drop PYTHONPATH AND VIRTUAL_ENV so pip/venv never target a foreign venv
    # (e.g. the Hermes agent environment on the dev host). We deliberately use
    # the venv we just created under .venv/ via sys.executable below.
    import os
    e = dict(os.environ)
    e.pop("PYTHONPATH", None)
    e.pop("VIRTUAL_ENV", None)
    if env:
        e.update(env)
    subprocess.run(cmd, check=False, env=e)


def smoke_import():
    py = ROOT / ".venv" / "bin" / "python"
    try:
        subprocess.run(
            [str(py), "-c",
             "import app.voice, app.brain.orchestrator, app.brain.agent_brain, app.brain.memory_manager"],
            cwd=str(ROOT), check=True, env={**__import__("os").environ, "PYTHONPATH": ""},
        )
        return True
    except Exception:
        return False


def install_voice_stack():
    """Best-effort install of MOON's FEMALE voice + optional dictation.

    Tries the right system package manager for the host OS (Debian/Ubuntu,
    Fedora/RHEL, Arch, macOS/brew) and falls back gracefully if none is
    available or the user lacks permission. The Python side (vosk/pyaudio)
    is optional for mic dictation and never blocks the core install.
    """
    import shutil

    pkg_cmd = None
    if shutil.which("apt-get"):
        pkg_cmd = "apt-get update && apt-get install -y espeak-ng sox"
    elif shutil.which("dnf"):
        pkg_cmd = "dnf install -y espeak-ng sox"
    elif shutil.which("yum"):
        pkg_cmd = "yum install -y espeak-ng sox"
    elif shutil.which("pacman"):
        pkg_cmd = "pacman -S --noconfirm espeak-ng sox"
    elif shutil.which("brew"):
        pkg_cmd = "brew install espeak sox"
    if pkg_cmd:
        _run(["bash", "-c", pkg_cmd])
    else:
        print("No supported system package manager found; skipping espeak-ng/sox "
              "system install. Install them manually for TTS: https://github.com/espeak-ng/espeak-ng")
    # Offline dictation (vosk + pyaudio) and the XTTS-v2 cloning engine (TTS).
    # Pulled best-effort; none of these block the core install.
    py = ROOT / ".venv" / "bin" / "python"
    _run([str(py), "-m", "pip", "install", "vosk", "pyaudio"])
    # NOTE: Coqui `TTS` (XTTS-v2 cloning engine) is intentionally NOT installed
    # here — it requires Python <3.12 and fails to build on 3.13. For neural voice
    # cloning, run MOON in a py3.11 venv or supply an OpenAI key with quota; the
    # cloning pipeline in app/voice_engine.py activates automatically when TTS exists.
    try:
        _run([str(py), "-m", "pip", "install", "openai"])
    except Exception as exc:  # noqa: BLE001
        print("openai install skipped:", exc)
    print("Voice stack: espeak-ng+sox for TTS (system, best-effort); "
          "XTTS-v2 for local cloning + openai for cloud female; "
          "vosk+pyaudio optional for mic dictation.")


def install_kokoro_voice():
    """Download Kokoro-ONNX model + voices so MOON's female voice works
    out-of-the-box (offline, no cloud key). Best-effort: a network failure
    must NOT break the install — voice_engine also lazy-downloads on first use.
    """
    import urllib.request
    cache = Path.home() / ".cache" / "kokoro-onnx"
    cache.mkdir(parents=True, exist_ok=True)
    base = "https://github.com/thewh1teagle/kokoro-onnx/releases/download/model-files-v1.0"
    targets = {
        "kokoro-v1.0.onnx": f"{base}/kokoro-v1.0.onnx",
        "voices-v1.0.bin": f"{base}/voices-v1.0.bin",
    }
    for name, url in targets.items():
        dest = cache / name
        if dest.exists() and dest.stat().st_size > 1_000_000:
            print(f"Kokoro asset present: {name}")
            continue
        print(f"Downloading Kokoro voice asset: {name} ...")
        try:
            urllib.request.urlretrieve(url, str(dest))
            print(f"  -> {dest.stat().st_size // 1_000_000} MB")
        except Exception as exc:  # noqa: BLE001
            print(f"  Kokoro asset download skipped (will lazy-fetch on first use): {exc}")


def verify_install():
    """Post-install end-to-end check: assert the critical subsystems actually
    work (no fake success). Returns True only if voice+agent/tool import paths are
    healthy. Runs best-effort; a soft failure prints guidance rather than aborting
    the install (the operator can re-run `make test`)."""
    import os
    e = dict(os.environ)
    e.pop("PYTHONPATH", None)
    e.pop("VIRTUAL_ENV", None)
    py = ROOT / ".venv" / "bin" / "python"
    script = (
        "import sys; sys.path.insert(0, '.')\n"
        "try:\n"
        "    from app.voice_engine import VoiceEngine\n"
        "    from app.config.settings import get_settings\n"
        "    ve = VoiceEngine(settings=get_settings())\n"
        "    bs = ve.backend_status()\n"
        "    print('VOICE backends:', {k: bs[k] for k in ('kokoro','espeak','openai') if k in bs})\n"
        "    from app.brain.orchestrator import Orchestrator\n"
        "    print('ORCHESTRATOR importable: OK')\n"
        "    print('INSTALL_VERIFY: OK')\n"
        "except Exception as exc:\n"
        "    print('INSTALL_VERIFY: DEGRADED', exc)\n"
    )
    try:
        r = subprocess.run([str(py), "-c", script], cwd=str(ROOT),
                           env=e, capture_output=True, text=True, timeout=120)
        out = (r.stdout or "") + (r.stderr or "")
        print(out.strip().splitlines()[-1] if out.strip() else "INSTALL_VERIFY: NO OUTPUT")
        return "INSTALL_VERIFY: OK" in out
    except Exception as exc:  # noqa: BLE001
        print("INSTALL_VERIFY: ERROR", exc)
        return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--no-env", action="store_true")
    ap.add_argument("--no-venv", action="store_true",
                    help="skip venv creation + dependency install (assume .venv exists; "
                         "used when install.sh has already prepared the environment)")
    ap.add_argument("--no-voice", action="store_true", help="skip voice stack install")
    ap.add_argument("--no-models", action="store_true", help="skip Ollama model pull")
    args = ap.parse_args()
    if not args.no_env and not args.no_venv:
        _run([sys.executable, "-m", "venv", ".venv"])  # _run already drops PYTHONPATH
        py = ROOT / ".venv" / "bin" / "python"
        _run([str(py), "-m", _PKG, "install", "--upgrade", _PKG])
        _run([str(py), "-m", _PKG, "install", "-r", "requirements.txt"])
        ensure_env_file()
        if not args.no_models:
            try:
                install_models()
            except Exception as exc:  # noqa: BLE001
                print("Model pull skipped:", exc)
    if not args.no_voice:
        try:
            install_voice_stack()
        except Exception as exc:  # noqa: BLE001
            print("Voice stack install skipped:", exc)
        try:
            install_kokoro_voice()
        except Exception as exc:  # noqa: BLE001
            print("Kokoro voice asset download skipped:", exc)
    print("Setup complete. Launch the UI with: make serve  (http://127.0.0.1:8777)")
    print("Female voice companion: make voice")
    print("Smoke import:", "OK" if smoke_import() else "FAILED")
    verify_install()


if __name__ == "__main__":
    main()
