#!/usr/bin/env python3
"""
MOON Setup Wizard -- first-run interactive configuration (like Ollama / n8n / etc).

Walks the operator through the key choices, writes a gitignored .env, then
hands off to the real installer (install_moon_full.py) for the actual
install + verification. Idempotent and non-destructive: if .env already
exists it is preserved and the wizard only fills gaps / asks to overwrite.

Usage:
    python3 setup_wizard.py            # interactive
    python3 setup_wizard.py --yes       # accept all recommended defaults (one-click)
    python3 setup_wizard.py --no-start  # build .env but don't run the installer

Safe: API keys are read with getpass (no echo) and written ONLY to .env
(which is gitignored). Nothing is logged.
"""
from __future__ import annotations

import argparse
import getpass
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
ENV = ROOT / ".env"


# ---- tiny colored prompt helpers ------------------------------------------
def _c(code, s):
    if sys.stdout.isatty():
        return f"\033[{code}m{s}\033[0m"
    return s


def info(s):   print(_c("36", f"[MOON] {s}"))
def ok(s):     print(_c("32", f"[ OK ] {s}"))
def warn(s):   print(_c("33", f"[!! ] {s}"))
def head(s):   print("\n" + _c("35", "=== " + s + " ==="))


def ask(question, default="", opts=None):
    """Prompt with optional choices. Returns the chosen string."""
    if opts:
        suffix = " (" + "/".join(opts) + f") [{default}]: "
    else:
        suffix = f" [{default}]: " if default else ": "
    while True:
        try:
            ans = input(_c("36", "  ? ") + question + suffix).strip()
        except EOFError:
            ans = default
        if not ans and default:
            return default
        if opts and ans not in opts:
            warn(f"Please choose one of: {', '.join(opts)}")
            continue
        return ans


def ask_secret(question):
    """Read a secret without echo. Returns '' if skipped (empty input)."""
    try:
        val = getpass.getpass(_c("36", "  ? ") + question + " [skip]: ")
    except EOFError:
        val = ""
    return val.strip()


def yes_no(question, default=True):
    d = "Y/n" if default else "y/N"
    a = ask(question, default=d, opts=["y", "n", "Y", "N", ""])
    if a == "":
        return default
    return a.lower() == "y"


def build_env(answers: dict) -> str:
    """Render a complete .env from the wizard answers (local-first defaults)."""
    backend = answers["backend"]
    model_base_url = answers.get("model_base_url", "http://127.0.0.1:11434/v1")
    model_name = answers.get("model_name", "qwen3:0.6b")
    model_api_key = answers.get("model_api_key", "not-required-for-local")
    strong_url = answers.get("strong_url", "")
    strong_name = answers.get("strong_name", "qwen3:1.7b")

    lines = [
        "# MOON local environment -- generated by setup_wizard.py",
        "# This file is gitignored -- never commit secrets.",
        "",
        "# Local OpenAI-compatible model endpoint.",
        f"MODEL_BASE_URL={model_base_url}",
        f"MODEL_NAME={model_name}",
        f"MODEL_API_KEY={model_api_key}",
        "",
        "# Embeddings (offline fallback when EMBEDDING_BASE_URL is blank).",
        "EMBEDDING_BASE_URL=",
        "EMBEDDING_MODEL=all-MiniLM-L6-v2",
        "EMBEDDING_DIM=384",
        "",
        "ENABLE_AGENT_VALIDATION=true",
        "ENABLE_AUTO_LEARNING=true",
        "ENABLE_BROWSER_AUTOMATION=true",
        "ENABLE_OCR=true",
        "ENABLE_PDF=true",
        "",
        f"AUTHORIZED_TARGETS={answers.get('targets', '127.0.0.1,localhost,192.168.0.0/16,10.0.0.0/8')}",
        "",
        f"STRONG_MODEL_NAME={strong_name}",
        f"STRONG_MODEL_BASE_URL={strong_url}",
        "",
        f"GITHUB_REPO={answers.get('github_repo', 'https://github.com/crsuvo100-gif/MOON')}",
        "",
        "# --- OpenAI-compatible FALLBACK backend (used only if local fails) ---",
        f"OPENAI_API_KEY={answers.get('openai_key', '')}",
        "OPENAI_BASE_URL=https://api.openai.com/v1",
        f"OPENAI_MODEL={answers.get('openai_model', 'gpt-4o-mini')}",
        "",
        "# --- OpenRouter FALLBACK backend (secondary) ---",
        f"OPENROUTER_API_KEY={answers.get('openrouter_key', '')}",
        "OPENROUTER_BASE_URL=https://openrouter.ai/api/v1",
        f"OPENROUTER_MODEL={answers.get('openrouter_model', 'openai/gpt-4o-mini')}",
        "",
        "# --- Hugging Face FALLBACK backend (tertiary) ---",
        f"HUGGINGFACE_API_KEY={answers.get('hf_key', '')}",
        "HUGGINGFACE_BASE_URL=https://router.huggingface.co",
        f"HUGGINGFACE_MODEL={answers.get('hf_model', 'meta-llama/Llama-3.1-8B-Instruct')}",
        "",
        "# --- Telegram channel (optional) ---",
        f"TELEGRAM_BOT_TOKEN={answers.get('tg_token', '')}",
        f"TELEGRAM_CHAT_ID={answers.get('tg_chat', '')}",
        "TELEGRAM_POLL_TIMEOUT=30",
        "",
        "# --- Terminal remote-access authorization gate (blank = local-only) ---",
        f"MOON_TERMINAL_TOKEN={answers.get('term_token', '')}",
        "",
    ]
    return "\n".join(lines) + "\n"


def run_wizard() -> dict:
    answers = {}
    head("MOON SETUP WIZARD")
    info("Welcome. This configures MOON for first run. Press ENTER to accept "
         "the [recommended] default, or type a different value.")
    info("Your answers are saved to .env (gitignored). Nothing is sent anywhere.")

    # 1. Model backend
    head("1. Model backend")
    info("MOON reasons through an LLM. Local Ollama is private, offline, and "
         "recommended. Cloud gives stronger models but needs a key.")
    backend = ask("Model backend", default="local",
                  opts=["local", "openai", "openrouter", "huggingface"])
    answers["backend"] = backend
    if backend == "local":
        answers["model_base_url"] = "http://127.0.0.1:11434/v1"
        answers["model_name"] = ask("Local model name (must be pulled by Ollama)",
                                     default="qwen3:0.6b")
        answers["model_api_key"] = "not-required-for-local"
        answers["strong_name"] = ask("Strong model (accuracy-critical tasks)",
                                      default="qwen3:1.7b")
        answers["strong_url"] = ""
    else:
        base = {"openai": "https://api.openai.com/v1",
                "openrouter": "https://openrouter.ai/api/v1",
                "huggingface": "https://router.huggingface.co"}[backend]
        answers["model_base_url"] = base
        answers["model_name"] = ask("Model id", default="gpt-4o-mini")
        key = ask_secret(f"API key for {backend} (leave blank to skip)")
        answers["model_api_key"] = key or "not-required-for-local"
        answers["strong_name"] = answers["model_name"]
        answers["strong_url"] = base

    # 2. Cloud fallback keys (optional, improves reliability)
    head("2. Optional cloud fallback (recommended to leave blank for local)")
    info("If the local model is busy/unavailable, MOON can fall back to a cloud "
         "endpoint. Blank = local-only. These are optional.")
    answers["openai_key"] = ask_secret("OpenAI API key (skip)")
    answers["openrouter_key"] = ask_secret("OpenRouter API key (skip)")
    answers["hf_key"] = ask_secret("HuggingFace API key (skip)")

    # 3. Telegram channel (optional)
    head("3. Telegram bot (optional remote channel)")
    if yes_no("Enable Telegram channel?", default=False):
        answers["tg_token"] = ask_secret("Telegram bot token (@BotFather)")
        answers["tg_chat"] = ask("Authorized chat id (blank = any)", default="")
    else:
        answers["tg_token"] = ""
        answers["tg_chat"] = ""

    # 4. Authorized targets (cyber ops safety boundary)
    head("4. Authorized scan targets (safety boundary)")
    info("MOON's active cyber tools only operate on hosts you explicitly own.")
    answers["targets"] = ask("Comma-separated hosts/CIDRs",
                              default="127.0.0.1,localhost,192.168.0.0/16,10.0.0.0/8")

    # 5. Remote access token (optional)
    head("5. Remote access (optional)")
    if yes_no("Require a bearer token to expose MOON's terminal remotely?",
              default=False):
        answers["term_token"] = ask_secret("Terminal bearer token")
    else:
        answers["term_token"] = ""

    # 6. Final confirm
    head("Ready")
    info(f"Backend: {backend}  |  Model: {answers.get('model_name')}  |  "
         f"Telegram: {'yes' if answers['tg_token'] else 'no'}  |  "
         f"Remote token: {'yes' if answers['term_token'] else 'no'}")
    return answers


def write_env(answers: dict, overwrite: bool):
    if ENV.exists() and not overwrite:
        warn(f".env already exists -- keeping it. (Use --force to regenerate.)")
        return False
    ENV.write_text(build_env(answers), encoding="utf-8")
    ok(f".env written ({ENV})")
    return True


def main():
    ap = argparse.ArgumentParser(description="MOON setup wizard")
    ap.add_argument("--yes", action="store_true",
                   help="accept all recommended defaults (non-interactive)")
    ap.add_argument("--force", action="store_true",
                   help="overwrite an existing .env")
    ap.add_argument("--no-start", action="store_true",
                   help="write .env only; do not run the installer")
    args = ap.parse_args()

    # Default answers for --yes (one-click).
    if args.yes:
        answers = {
            "backend": "local",
            "model_base_url": "http://127.0.0.1:11434/v1",
            "model_name": "qwen3:0.6b",
            "model_api_key": "not-required-for-local",
            "strong_name": "qwen3:1.7b",
            "strong_url": "",
            "openai_key": "", "openrouter_key": "", "hf_key": "",
            "tg_token": "", "tg_chat": "",
            "targets": "127.0.0.1,localhost,192.168.0.0/16,10.0.0.0/8",
            "term_token": "",
        }
        info("Non-interactive mode: using recommended local-first defaults.")
    else:
        answers = run_wizard()

    write_env(answers, args.force)

    if args.no_start:
        info("Skipping installer (--no-start). Run ./install.sh to install.")
        return 0

    # Hand off to the real installer for actual install + verification.
    installer = ROOT / "install_moon_full.py"
    if not installer.exists():
        warn("install_moon_full.py not found -- cannot continue install.")
        return 1
    info("Running the real installer (install_moon_full.py) ...")
    env = dict(os.environ)
    env.pop("PYTHONPATH", None)
    rc = subprocess.run([sys.executable, str(installer), "--no-service"],
                        env=env, cwd=str(ROOT)).returncode
    if rc != 0:
        warn("Installer reported issues. Review the output above.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
