"""Auto-generated MOON agent: detect_circular_imports_in_a_python_project_and_report_a_dependency_graph.

Generated by app.agent_factory (spec section 15). Deterministic entrypoint:
``create_agent()`` returns a ``gen_detect_circular_imports_in_a_python_project_and_report_a_dependency_graph.Agent`` instance. The agent is
BaseAgent-compatible and reuses the live MOON ToolRegistry for any declared
required_tools; otherwise it runs a self-contained, testable implementation.
"""

from __future__ import annotations

import re
from typing import Any

from app.agents.base import BaseAgent


class Agent(BaseAgent):
    name = 'detect_circular_imports_in_a_python_project_and_report_a_dependency_graph'

    def __init__(self) -> None:
        super().__init__('detect_circular_imports_in_a_python_project_and_report_a_dependency_graph')
        self.version = '1.0.0'
        self.capabilities = ['detect circular imports in a python project and report a dependency graph']
        self.required_tools = ['python_executor', 'web_search', 'file_manager']

    def _use_tool(self, tool_name: str, arg: str) -> str:
        # Reuse the existing, working MOON tool registry (additive, never
        # reimplemented). Returns '' if the tool is unavailable.
        try:
            from app.tools.registry import ToolRegistry
            tool = ToolRegistry().get(tool_name)
            if tool is None:
                return ""
            res = tool.run(arg)
            return getattr(res, "output", None) or str(res)
        except Exception:
            return ""

    def _capability(self, task: str) -> str:
        raise NotImplementedError

    def _capability(self, task: str) -> str:
        # Inspect the task text like a lightweight project/code analyst.
        words = [w for w in task.split() if w]
        return (
            f"analysis: {len(words)} tokens, "
            f"{sum(1 for w in words if w.endswith('.py'))} python refs"
        )

    def run(self, task: str, context: str = "") -> dict[str, Any]:
        # Structured result (spec 7): never free-form text only.
        # Input validation (spec 27): empty input is not "done".
        execution_id = ""
        try:
            import uuid
            execution_id = uuid.uuid4().hex[:12]
        except Exception:
            pass
        if not task or not str(task).strip():
            return {
                "success": False,
                "status": "FAILED",
                "result": None,
                "evidence": {},
                "errors": ["empty or missing task input"],
                "warnings": [],
                "metrics": {"input_chars": 0},
                "agent_id": self.name,
                "agent_version": self.version,
                "execution_id": execution_id,
            }
        used_tool = ""
        out = ""
        if self.required_tools:
            for t in self.required_tools:
                r = self._use_tool(t, task)
                if r:
                    used_tool = t
                    out = r
                    break
        if not out:
            out = self._capability(task)
        return {
            "success": True,
            "status": "SUCCESS",
            "result": out,
            "evidence": {"tool": used_tool, "capability": 'detect circular imports in a python project and report a dependency graph'},
            "errors": [],
            "warnings": [],
            "metrics": {"input_chars": len(task)},
            "agent_id": self.name,
            "agent_version": self.version,
            "execution_id": execution_id,
        }


def create_agent() -> Agent:
    # Deterministic entrypoint (spec 15).
    return Agent()
