const $=id=>document.getElementById(id);const state={ws:null,connected:false,job:null,started:Date.now(),demo:true};
const events=$('events'),out=$('terminalOutput'),eventOutput=$('eventOutput');
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function event(tag,msg){const d=new Date();const e=document.createElement('div');e.className='event';e.innerHTML=`<span class="time">${d.toLocaleTimeString('en-GB')}</span><span class="tag">[${esc(tag)}]</span>${esc(msg)}`;events.prepend(e);while(events.children.length>80)events.lastChild.remove()}
function logTerminal(s){out.textContent+=s;out.scrollTop=out.scrollHeight}
function setState(s){const stage=$('avatarStage');stage.classList.remove('listening','thinking','speaking','executing');if(s!=='idle')stage.classList.add(s);$('avatarState').textContent=s.toUpperCase();$('voiceState').textContent=s==='listening'?'LISTENING':s==='speaking'?'SPEAKING':s==='thinking'?'PROCESSING':s==='executing'?'EXECUTING':'READY';$('voiceLabel').textContent=s==='listening'?'LISTENING...':s==='speaking'?'SPEAKING...':s==='thinking'?'THINKING...':s==='executing'?'EXECUTING...':'STANDBY';$('thinkingState').textContent=s==='thinking'?'RECURSING':'ACTIVE';event('MOON',`Avatar state → ${s}`)}
function setMood(m){document.querySelectorAll('[data-mood]').forEach(x=>x.classList.toggle('active',x.dataset.mood===m));event('MOOD',`Emotion set to ${m.toUpperCase()}`)}
function demoMetrics(){['cpu','ram','disk','net'].forEach((id,i)=>$(id).textContent=(12+Math.floor(Math.random()*35)+i*3)+'%');$('temp').textContent=(39+Math.floor(Math.random()*7))+'°C';$('fan').textContent=(1200+Math.floor(Math.random()*180))+' RPM'}
function connect(){if(state.ws)try{state.ws.close()}catch{};try{const ws=new WebSocket(`ws://${location.hostname}:8765/moon`);state.ws=ws;ws.onopen=()=>{state.connected=true;state.demo=false;$('conn').textContent='ONLINE';$('statusText').textContent='CONNECTED';event('SYSTEM','MOON connected to system');ws.send(JSON.stringify({type:'hello',agent:'MOON_NEXUS_V3_UI',role:'UI',protocol:'MOON_AGENT_BRIDGE/1'}));ws.send(JSON.stringify({type:'system.info'}))};ws.onmessage=e=>{try{handle(JSON.parse(e.data))}catch{}};ws.onclose=()=>{state.connected=false;state.demo=true;$('conn').textContent='OFFLINE';$('statusText').textContent='DISCONNECTED';event('SYSTEM','Bridge unavailable — visual demo mode active')};ws.onerror=()=>{}}catch{state.demo=true}}
function send(o){if(state.ws?.readyState===1){state.ws.send(JSON.stringify(o));return true}return false}
function handle(e){if(e.type==='terminal.ready'){event('SUCCESS','Terminal bridge ready');$('fnTotal').textContent=(e.capabilities||[]).length||312}else if(e.type==='terminal.output'){logTerminal(e.data||'');eventOutput.textContent+=e.data||''}else if(e.type==='terminal.result'){state.job=null;event('SUCCESS',`Command completed with exit ${e.exit_code}`)}else if(e.type==='terminal.start'){state.job=e.id;setState('executing');logTerminal(`\n[EXEC] ${e.command}\n`);event('COMMAND',e.command)}else if(e.type==='avatar.state'){setState(e.state||'idle');if(e.emotion)setMood(e.emotion)}else if(e.type==='avatar.speak'){setState('speaking');event('MOON',e.text||'Speaking');if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(e.text||''))}}else if(e.type==='system.info'){const s=e.system||{};event('SYSTEM',`${s.os||'OS'} / ${s.shell||'shell'} / ${s.python||'python'}`)}else if(e.type==='ui.pong'&&e.t){$('latency').textContent=Math.round(performance.now()-e.t)+' ms'}}
function execute(cmd){cmd=(cmd||$('cmd').value).trim();if(!cmd)return;if(send({type:'terminal.exec',id:'ui-'+Date.now(),command:cmd,timeout:300})){state.job='pending';$('cmd').value='';return}setState('executing');event('DEMO',`Simulated command: ${cmd}`);logTerminal(`\n$ ${cmd}\n`);setTimeout(()=>{logTerminal(`MOON DEMO: command accepted and queued.\n`);event('SUCCESS',`Demo execution finished: ${cmd}`);setState('idle')},650)}
$('send').onclick=()=>execute();$('execute').onclick=()=>execute();$('cmd').onkeydown=e=>{if(e.key==='Enter')execute()};$('clear').onclick=()=>{out.textContent='';eventOutput.textContent=''};$('stop').onclick=()=>{if(state.job)send({type:'terminal.cancel',id:state.job});setState('idle');event('CONTROL','Execution stop requested')};$('mic').onclick=()=>{setState('listening');event('VOICE','Microphone listening');setTimeout(()=>setState('thinking'),1200);setTimeout(()=>setState('idle'),2500)};
document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>setState(b.dataset.state));document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>setMood(b.dataset.mood));document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{setState('executing');execute(b.dataset.command)});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');event('NAV',`${b.textContent.trim()} opened`);if(b.dataset.panel!=='terminal')setState('thinking');setTimeout(()=>setState('idle'),900)});
function drawGraph(){const c=$('perf'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.scale(d,d);x.clearRect(0,0,r.width,r.height);const lines=[['#ff2638',.55],['#28cfe7',.35],['#a35bd8',.7]];lines.forEach(([col,amp],j)=>{x.strokeStyle=col;x.lineWidth=1;x.beginPath();for(let i=0;i<r.width;i+=4){const y=r.height/2+Math.sin(i*.09+j)*r.height*.14*amp+(Math.random()-.5)*r.height*.18*amp;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.stroke()})}
function particles(){const p=$('particles');for(let i=0;i<55;i++){const s=document.createElement('i');s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=(Math.random()*5)+'s';p.appendChild(s)}}
function boot(){particles();drawGraph();event('SYSTEM','MOON connected to system');event('SYSTEM','Memory core initialized');event('SYSTEM','Retriever service online');event('SYSTEM','Planner engine ready');event('TOOLS','138 tools loaded');event('FUNCTIONS','Functions registered: 312');event('VISION','Vision system online');event('VOICE','Voice system online');event('AVATAR','MOON Avatar interface ready');event('MOON','Awaiting your command...');logTerminal('MOON NEXUS v3.0 — TERMINAL ONLINE\n\nmoon@nexus:~$ ');setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('en-GB');$('date').textContent=new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}).toUpperCase();$('uptime').textContent=Math.floor((Date.now()-state.started)/3600000)+'h '+Math.floor((Date.now()-state.started)/60000)%60+'m';demoMetrics();drawGraph()},1000);setInterval(()=>{if(state.ws?.readyState===1){const t=performance.now();send({type:'ui.ping',t})}},3000);setTimeout(connect,300)}boot();
