const $=id=>document.getElementById(id);const state={ws:null,connected:false,job:null,started:Date.now(),demo:true,mic:false,speaking:false,logs:[]};
const avatarHuman={x:0,y:0,blinkUntil:0,blinkNext:performance.now()+2600,mouth:0};
const events=$('events'),out=$('terminalOutput'),eventOutput=$('eventOutput');
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function event(tag,msg){const d=new Date();const e=document.createElement('div');e.className='event';e.innerHTML=`<span class="time">${d.toLocaleTimeString('en-GB')}</span><span class="tag">[${esc(tag)}]</span>${esc(msg)}`;events.prepend(e);state.logs.unshift({time:d.toISOString(),tag,msg});while(events.children.length>100)events.lastChild.remove()}
function logTerminal(s){out.textContent+=s;out.scrollTop=out.scrollHeight;eventOutput.textContent+=s;eventOutput.scrollTop=eventOutput.scrollHeight}
function setState(s){const stage=$('avatarStage');stage.classList.remove('listening','thinking','speaking','executing','success','error','avatar-listening','avatar-thinking','avatar-speaking','avatar-executing');if(s!=='idle')stage.classList.add(s);if(s==='listening')stage.classList.add('avatar-listening');if(s==='thinking')stage.classList.add('avatar-thinking');if(s==='speaking')stage.classList.add('avatar-speaking');if(s==='executing')stage.classList.add('avatar-executing');state.speaking=s==='speaking';$('avatarState').textContent=s.toUpperCase();$('voiceState').textContent=s==='listening'?'LISTENING':s==='speaking'?'SPEAKING':s==='thinking'?'PROCESSING':s==='executing'?'EXECUTING':'READY';$('voiceLabel').textContent=s==='listening'?'LISTENING...':s==='speaking'?'SPEAKING...':s==='thinking'?'THINKING...':s==='executing'?'EXECUTING...':'STANDBY';$('thinkingState').textContent=s==='thinking'?'RECURSING':'ACTIVE';event('MOON',`Avatar state → ${s}`)}
function setMood(m){document.querySelectorAll('[data-mood]').forEach(x=>x.classList.toggle('active',x.dataset.mood===m));event('MOOD',`Emotion set to ${m.toUpperCase()}`);send({type:'avatar.expression',emotion:m,expression:m,gesture:'none'})}
function demoMetrics(){/* disabled: per real-state rule, gauges are driven by MOON's real moon.system telemetry, not fabricated random values */}
function connect(){try{const ws=new WebSocket(`ws://${location.hostname}:${window.MOON_BRIDGE_PORT || 8765}/moon`);state.ws=ws;ws.onopen=()=>{state.connected=true;state.demo=false;$('conn').textContent='ONLINE';$('statusText').textContent='CONNECTED';event('SYSTEM','MOON connected to system');ws.send(JSON.stringify({type:'hello',agent:'MOON_V3_1_UI',role:'UI',protocol:'MOON_AGENT_BRIDGE/1'}));ws.send(JSON.stringify({type:'system.info'}))};ws.onmessage=e=>{try{handle(JSON.parse(e.data))}catch(err){event('ERROR',err.message)}};ws.onclose=()=>{state.connected=false;state.demo=true;$('conn').textContent='OFFLINE';$('statusText').textContent='DISCONNECTED';event('SYSTEM','Bridge unavailable — visual/local mode active')};ws.onerror=()=>{}}catch{state.demo=true}}
function send(o){if(state.ws?.readyState===1){state.ws.send(JSON.stringify(o));return true}return false}
function speak(text){text=String(text||'').trim();if(!text)return;setState('speaking');$('avatarCaption').textContent=text;if('speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.pitch=1.02;u.onend=()=>setState('idle');speechSynthesis.speak(u)}else setTimeout(()=>setState('idle'),Math.min(6000,text.length*35))}
function handle(e){if(e.type==='terminal.ready'){event('SUCCESS','Terminal bridge ready');const caps=e.capabilities||[];if(caps.length&&$('fnTotal').textContent==='0')$('fnTotal').textContent=caps.length;if(caps.length){const grid=$('functionList');if(grid&&!grid.children.length){for(let i=1;i<=caps.length;i++){const b=document.createElement('button');b.className='fn-btn';b.textContent='fn_'+i;grid.appendChild(b)}}event('FUNCTIONS','Functions registered: '+caps.length)}}else if(e.type==='terminal.output'){logTerminal(e.data||'')}else if(e.type==='terminal.result'){state.job=null;event(e.exit_code===0?'SUCCESS':'ERROR',`Command completed with exit ${e.exit_code}`);setState(e.exit_code===0?'success':'error');setTimeout(()=>setState('idle'),900)}else if(e.type==='terminal.confirmation_required'){event('CONFIRM',`Awaiting confirmation: ${e.command}`);if(confirm(`MOON requires confirmation to run:\n\n${e.command}\n\nAllow?`)){send({type:'terminal.confirm',id:e.id,command:e.command});event('CONFIRM',`Confirmed: ${e.command}`)}else{send({type:'terminal.cancel',id:e.id});event('CONFIRM',`Declined: ${e.command}`)}}else if(e.type==='terminal.confirmed'){event(e.ok?'SUCCESS':'ERROR',`Confirmation result: ${e.reason||e.id}`)}else if(e.type==='terminal.start'){state.job=e.id;setState('executing');logTerminal(`\n[EXEC] ${e.command}\n`);event('COMMAND',e.command)}else if(e.type==='avatar.state'){setState(e.state||'idle');if(e.emotion)setMood(e.emotion)}else if(e.type==='avatar.speak'){speak(e.text||'')}else if(e.type==='moon.response'){const t=String(e.text||e.message||'').trim();if(t){event('MOON',t.slice(0,180));speak(t)}}else if(e.type==='moon.event'){event('MOON',JSON.stringify(e).slice(0,180));}else if(e.type==='moon.connection'){event('MOON',`Brain ${e.state||'unknown'}`)}else if(e.type==='system.info'){const s=e.system||{};event('SYSTEM',`${s.os||'OS'} / ${s.shell||'shell'} / ${s.python||'python'}`)}else if(e.type==='ui.pong'&&e.t){$('latency').textContent=Math.max(0,Math.round(performance.now()-e.t))+' ms'}else if(e.type==='moon.passthrough'){event('MOON',JSON.stringify(e.original).slice(0,180))}
else if(e.type==='moon.system'){const s=e.system||{};
  $('cpu').textContent=Math.round(s.cpu||0)+'%';$('ram').textContent=Math.round(s.ram||0)+'%';$('disk').textContent=Math.round(s.disk||0)+'%';
  let netPct=0,netMbps=0;if(s.net_sent_mb!==undefined){const now=Date.now();const tot=s.net_sent_mb+s.net_recv_mb;if(window.__prevNet!==undefined){const dmb=tot-window.__prevNet;const dt=Math.max(0.2,(now-window.__prevNetT)/1000);netMbps=(dmb*8/1000)/dt;netPct=Math.min(100,netMbps/1.0)}window.__prevNet=tot;window.__prevNetT=now;if(window.__bootNet===undefined)window.__bootNet=tot;$('dataFlow').textContent=((tot||0)/1e6).toFixed(2)+' TB / 10 TB'}else if(s.net!==undefined)netPct=s.net;
  $('net').textContent=Math.round(netPct)+'%';
  if(s.ram_used_gb!==undefined)$('ram').setAttribute('title',s.ram_used_gb+'GB used');
  $('temp').textContent=(s.temp_c!==undefined&&s.temp_c!==null)?Math.round(s.temp_c)+'°C':'—';
  $('cpuSub').textContent=(s.cpu_freq_ghz!==undefined&&s.cpu_freq_ghz!==null)?s.cpu_freq_ghz+' GHz':'—';
  $('ramSub').textContent=(s.ram_used_gb!==undefined)?(s.ram_used_gb+' / '+(s.ram_total_gb||'?')+' GB'):'—';
  $('diskSub').textContent=(s.disk_used_gb!==undefined)?(s.disk_used_gb+' / '+(s.disk_total_gb||'?')+' GB'):'—';
  $('netSub').textContent=netMbps?netMbps.toFixed(0)+' Mbps':'—';}
else if(e.type==='moon.agent.status'){const st=e.status||{};['BRAIN','MEMORY','RETRIEVER','PLANNER','TOOLS','VISION','LISTENER'].forEach(k=>{const li=[...document.querySelectorAll('#agentStatus li')].find(n=>n.textContent.includes(k));if(li){const b=li.querySelector('b');const val=st[k];if(b&&val!==undefined){b.textContent=val;const on=(val==='ONLINE'||val==='ACTIVE');li.style.color=on?'#39ff9e':'#ffcf5c';const dot=li.querySelector('i');if(dot)dot.style.background=on?'#39ff9e':'#ffcf5c'}}});
  if(st.FUNCTIONS!==undefined){const n=parseInt(st.FUNCTIONS,10)||0;$('fnTotal').textContent=n;const grid=$('functionList');if(grid){grid.innerHTML='';const names=st.tool_names||[];const cats={};names.forEach(x=>{const c=x.includes('_')?x.split('_')[0]:x;cats[c]=(cats[c]||0)+1});Object.keys(cats).sort().forEach(c=>{const b=document.createElement('button');b.className='fn-btn';b.textContent=c+': '+cats[c];grid.appendChild(b)});if(!names.length){for(let i=1;i<=n;i++){const b=document.createElement('button');b.className='fn-btn';b.textContent='fn_'+i;grid.appendChild(b)}}}event('FUNCTIONS','Functions registered: '+n)}}}function execute(cmd){cmd=(cmd||$('cmd').value).trim();if(!cmd)return;if(send({type:'terminal.exec',id:'ui-'+Date.now(),command:cmd,timeout:300})){state.job='pending';$('cmd').value='';return}setState('executing');event('LOCAL',`Demo command: ${cmd}`);logTerminal(`\n$ ${cmd}\n`);setTimeout(()=>{logTerminal('MOON LOCAL MODE: command queued. Connect MOON bridge for real execution.\n');event('SUCCESS','Local command simulation finished');setState('idle')},500)}
function openWorkspace(panel){const w=$('workspace'),title=$('workspaceTitle'),body=$('workspaceBody');w.classList.add('open');title.textContent=panel.toUpperCase();const cards={memory:['MEMORY INDEX','Retrieve, inspect and synchronize MOON memory.','Sync Memory'],tools:['TOOL REGISTRY','MOON-owned functions remain outside this UI bridge.','Request Capability Sync'],tasks:['TASK ORCHESTRATOR','Create or inspect tasks through MOON.','Send Task Request'],vault:['DATA VAULT','Open the configured working directory in the terminal.','List Vault'],settings:['MOON SETTINGS','Local UI preferences and connection controls.','Reconnect MOON'],chat:['MOON CHAT','Chat requests are forwarded to the connected MOON agent.','Open Chat']};if(panel==='chat'){body.innerHTML='<div class="chatbox"><div class="chatlog" id="chatlog"><div class="chatrow"><b>MOON:</b> Online and ready.</div></div><div class="chatinput"><input id="chatInput" placeholder="Message MOON..."><button id="chatSend">SEND</button></div></div>';const sendChat=()=>{const inp=$('chatInput');const text=inp.value.trim();if(!text)return;addChat('YOU',text);if(send({type:'ui.action',action:'moon.chat',payload:{text}})){addChat('MOON','Request forwarded to MOON.')}else{addChat('MOON','MOON bridge is offline. Local UI is ready.')}inp.value='';};$('chatSend').onclick=sendChat;$('chatInput').onkeydown=e=>{if(e.key==='Enter')sendChat()};return}const c=cards[panel]||cards.settings;body.innerHTML=`<div class="workspace-grid"><div class="workspace-card"><h3>${c[0]}</h3><p>${c[1]}</p><button id="workspaceAction">${c[2]}</button></div><div class="workspace-card"><h3>BRIDGE</h3><p>Connection: ${state.connected?'ONLINE':'OFFLINE'}</p><button id="workspaceReconnect">Reconnect</button></div><div class="workspace-card"><h3>STATUS</h3><p>All existing MOON intelligence remains agent-owned.</p><button id="workspaceTerminal">Open Terminal</button></div></div>`;$('workspaceAction').onclick=()=>{send({type:'ui.action',action:'moon.'+panel,payload:{source:'moon_ui'}});event('UI',`${panel} request sent to MOON`)};$('workspaceReconnect').onclick=connect;$('workspaceTerminal').onclick=()=>{w.classList.remove('open');document.querySelector('[data-panel="terminal"]').click()}}
function addChat(who,text){const c=$('chatlog');if(!c)return;const d=document.createElement('div');d.className='chatrow';d.innerHTML=`<b>${esc(who)}:</b> ${esc(text)}`;c.appendChild(d);c.scrollTop=c.scrollHeight}
$('workspaceClose').onclick=()=>$('workspace').classList.remove('open');$('send').onclick=()=>execute();$('execute').onclick=()=>execute();$('cmd').onkeydown=e=>{if(e.key==='Enter')execute()};$('clear').onclick=()=>{out.textContent='';eventOutput.textContent='';event('CONTROL','Terminal cleared')};$('stop').onclick=()=>{if(state.job)send({type:'terminal.cancel',id:state.job});state.job=null;setState('idle');event('CONTROL','Execution stop requested')};$('closeUi').onclick=()=>{event('UI','Close requested — browser controls the window')};
document.querySelectorAll('[data-state]').forEach(b=>b.onclick=()=>{setState(b.dataset.state);if(b.dataset.state==='speaking')speak('Hello. I am MOON. How can I assist you today?')});document.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>setMood(b.dataset.mood));document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>execute(b.dataset.command));document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));b.classList.add('active');if(b.dataset.panel==='terminal'){$('workspace').classList.remove('open');return}openWorkspace(b.dataset.panel);event('NAV',`${b.textContent.trim()} opened`)});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{if(b.dataset.command)execute(b.dataset.command);else event('TAB',b.textContent+' selected')});
function toggle(id){const el=$(id);el.classList.toggle('on');event('VOICE',`${id==='voiceIn'?'Voice input':'Voice output'} ${el.classList.contains('on')?'ON':'OFF'}`)}$('voiceIn').onclick=()=>toggle('voiceIn');$('voiceOut').onclick=()=>toggle('voiceOut');
let recognition=null;if('SpeechRecognition'in window||'webkitSpeechRecognition'in window){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new SR();recognition.lang='en-US';recognition.interimResults=false;recognition.onstart=()=>{state.mic=true;$('mic').classList.add('active');setState('listening');event('VOICE','Speech recognition listening')};recognition.onresult=e=>{const t=e.results[0][0].transcript;event('VOICE','Heard: '+t);$('cmd').value=t;setState('thinking');setTimeout(()=>{if(t.toLowerCase().startsWith('moon ')){speak('I heard you.');}execute(t)},400)};recognition.onerror=e=>event('VOICE','Recognition error: '+e.error);recognition.onend=()=>{state.mic=false;$('mic').classList.remove('active');if($('avatarState').textContent==='LISTENING')setState('idle')}}
$('mic').onclick=()=>{if(recognition){if(state.mic)recognition.stop();else recognition.start()}else{setState('listening');event('VOICE','Speech recognition is unavailable in this browser');setTimeout(()=>setState('idle'),1400)}};
function avatarHumanLoop(){const stage=$('avatarStage'),head=$('avatarHead'),gaze=$('gazeTarget');if(!stage||!head)return;const now=performance.now();if(now>avatarHuman.blinkNext){avatarHuman.blinkUntil=now+140;avatarHuman.blinkNext=now+1800+Math.random()*4200}const blink=now<avatarHuman.blinkUntil;const idleX=Math.sin(now/3600)*1.1,idleY=Math.cos(now/4200)*.7,bob=Math.sin(now/1900)*1.8,sway=Math.sin(now/2700)*1.2;head.style.transform=`translate3d(${sway}px,${bob}px,26px) rotateX(${avatarHuman.y*.055+idleY}deg) rotateY(${avatarHuman.x*.07+idleX}deg)`;head.style.opacity=blink?'0.995':'1';stage.style.setProperty('--mouth-scale',String(1+avatarHuman.mouth*.55));avatarHuman.mouth += ((state.speaking)?(0.3+Math.abs(Math.sin(now/95))*.7):0-avatarHuman.mouth)*.16;if(!state.speaking)avatarHuman.mouth*=.90;if(gaze){gaze.style.left=`${50+avatarHuman.x*6}%`;gaze.style.top=`${38+avatarHuman.y*4}%`}requestAnimationFrame(avatarHumanLoop)}
function bindAvatarHumanInteraction(){const stage=$('avatarStage');if(!stage)return;stage.addEventListener('pointermove',e=>{const r=stage.getBoundingClientRect();avatarHuman.x=((e.clientX-r.left)/r.width-.5)*2;avatarHuman.y=((e.clientY-r.top)/r.height-.5)*2;if(state.connected)send({type:'avatar.interaction',interaction:'gaze',x:avatarHuman.x,y:avatarHuman.y,attention:'user',gesture:'look'})});stage.addEventListener('pointerleave',()=>{avatarHuman.x=0;avatarHuman.y=0});stage.addEventListener('click',()=>{setState('listening');event('AVATAR','MOON avatar attention engaged');send({type:'avatar.interaction',interaction:'attention',attention:'user',gesture:'look'})})}
function drawGraph(){const c=$('perf'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,r.width,r.height);const cols=['#ff2638','#27d7e8','#a35bd8'];cols.forEach((col,j)=>{x.strokeStyle=col;x.lineWidth=1;x.beginPath();for(let i=0;i<r.width;i+=4){const y=r.height/2+Math.sin(i*.08+j*1.7)*r.height*.12+(Math.random()-.5)*r.height*.2;if(i===0)x.moveTo(i,y);else x.lineTo(i,y)}x.stroke()})}
function particles(){const p=$('particles');for(let i=0;i<60;i++){const s=document.createElement('i');s.style.position='absolute';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.width='2px';s.style.height='2px';s.style.background='#ff2638';s.style.opacity='.25';p.appendChild(s)}}
function avatarFx(){const c=$('avatarFx'),ctx=c.getContext('2d');function frame(){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);const t=performance.now()/1000;for(let i=0;i<90;i++){const a=i*2.399+t*(.1+(i%5)*.015),rad=Math.min(r.width,r.height)*(.18+(i%17)/80);const x=r.width/2+Math.cos(a)*rad,y=r.height*.44+Math.sin(a)*rad*.62;ctx.fillStyle=`rgba(255,38,56,${.08+(i%7)/70})`;ctx.fillRect(x,y,1.4,1.4)}requestAnimationFrame(frame)}frame()}
function boot(){particles();drawGraph();avatarFx();bindAvatarHumanInteraction();avatarHumanLoop();event('SYSTEM','MOON connected to system');event('SYSTEM','Memory core initialized');event('SYSTEM','Retriever service online');event('SYSTEM','Planner engine ready');event('VISION','Vision system offline');event('VOICE','Voice system online');event('AVATAR','3D holographic avatar layer ready');event('MOON','Awaiting your command...');logTerminal('MOON v3.0 — TERMINAL ONLINE\n\nMOON$ ');setInterval(()=>{$('clock').textContent=new Date().toLocaleTimeString('en-GB');$('date').textContent=new Date().toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}).toUpperCase();$('uptime').textContent=Math.floor((Date.now()-state.started)/3600000)+'h '+Math.floor((Date.now()-state.started)/60000)%60+'m';drawGraph()},1000);setInterval(()=>{if(state.ws?.readyState===1){const t=performance.now();send({type:'ui.ping',t})}},3000);window.addEventListener('resize',drawGraph);setTimeout(connect,250)}boot();